travis:
  secure:
    BINSTAR_TOKEN: kDTIqpTwqoaVMwu+f8H2zFw94x6DD+HwWhJdB01ZHfNZ6jOlajsvx2IjciS48HSyoxouDgH5XyhCxu1LGHaHbHTZ8ZdndLV5Zb5oBxQt3yXwGmjn4k0Jb2kCN6xrFrWJ75CGaFvdn6+JMaKHQLrr0myS5POFia3gRyH+DxkV8J91fmEe54uyNaBcC0P1DuZ49Ual5rDO/LuzwpKF3+D9W8D5Zx4tEGaXrdTcF1vkCUYpjCrNDUPn4CGaXjMwG+N5SG6NYmrU66FLI6ir74Q6Rn1OrQuJPaHhYtAMmqDemLmEu8LmNF5hPh2NmiRdRccdGet8d+OsfDZ5UoX2nNRN2v1c5/mfrsx38hyq+OPmZx2dUDy7R1y+MtWQDK2UCq/ldnmAhxnyISlGLWeOuGPAX5trcmaUFH180khIR5T2bvdEeMftya6gPonFz9UqrYautY6DZQnTRUBtw1dZXkunHybWd9pZyBRja3i4lgFJXf8O1E1NZWxrYlvc+ZQOQlKJRic2PAdrSZ3pBkX/Qf1pg3XUSiQk679KFoT2hAvZ23dNK4IJoKqTSm6bYuT/TyvlCp0eiLMN7PzaaMRVFwMwnnYg6i9i8VXjLbg5VMtUehBpj3yL9D/LlIBG6E75laEKA5+IH8e/3Va2dDFa2XfTjXuNZUz6pwpbGzkHqzwGNcs=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
